name: Validate PR
on:
  pull_request:
    branches: [main]
jobs:
  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - run: |
          dotnet tool restore
          dotnet csharpier --check .
